apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaos-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kaos-operator
subjects:
- kind: ServiceAccount
  name: kaos-operator
  namespace: kaos-system
